package com.cloud.picture.space.backend.api.aliYun.model.EditPicture;


import cn.hutool.core.annotation.Alias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.io.Serializable;

/**
 * @Author: StartEnd
 * @CreateTime: 2026-03-19  13:54
 * @Description: AI 扩图请求体
 */
@Data
public class CreateOutPaintingTaskRequest implements Serializable {

    /**
     * 模型名称
     * 固定值：image-out-painting
     */
    private String model = "image-out-painting";

    /**
     * 输入图像信息
     */
    private Input input;

    /**
     * 图像处理参数
     */
    private Parameters parameters;

    /**
     * 输入图像基本信息
     */
    @Data
    public static class Input implements Serializable {

        /**
         * 图像 URL 地址或 Base64 数据
         * 需为公网可访问的 HTTP 或 HTTPS 地址
         * 图像限制：
         * - 格式：JPG、JPEG、PNG、HEIF、WEBP
         * - 大小：不超过 10MB
         * - 分辨率：512×512 至 4096×4096 像素
         */
        @Alias("image_url")
        private String imageUrl;
    }

    /**
     * 输出图像处理参数
     */
    @Data
    public static class Parameters implements Serializable {

        /**
         * 逆时针旋转角度
         * 默认值：0
         * 取值范围：[0, 359]，单位为度
         */
        private Integer angle;

        /**
         * 输出图像的宽高比
         * 默认值："" (不设置)
         * 可选值：["", "1:1", "3:4", "4:3", "9:16", "16:9"]
         */
        @Alias("output_ratio")
        private String outputRatio;

        /**
         * 水平方向扩展比例
         * 默认值：1.0
         * 取值范围：[1.0, 3.0]
         * 示例：输入 1000×1000，x_scale=2.0 → 输出 2000×1000（左右各添加 500 像素）
         */
        @Alias("x_scale")
        @JsonProperty("xScale")
        private Float xScale;

        /**
         * 垂直方向扩展比例
         * 默认值：1.0
         * 取值范围：[1.0, 3.0]
         * 示例：输入 1000×1000，y_scale=2.0 → 输出 1000×2000（上下各添加 500 像素）
         */
        @Alias("y_scale")
        @JsonProperty("yScale")
        private Float yScale;

        /**
         * 上方添加像素数量
         * 默认值：0
         * 限制：top_offset + bottom_offset < 3 × 输入图像高度
         * 示例：输入 1000×1000，top_offset=500 → 输出 1000×1500（仅在上方添加 500 像素）
         */
        @Alias("top_offset")
        private Integer topOffset;

        /**
         * 下方添加像素数量
         * 默认值：0
         * 限制：top_offset + bottom_offset < 3 × 输入图像高度
         * 示例：输入 1000×1000，bottom_offset=500 → 输出 1000×1500（仅在下方添加 500 像素）
         */
        @Alias("bottom_offset")
        private Integer bottomOffset;

        /**
         * 左侧添加像素数量
         * 默认值：0
         * 限制：left_offset + right_offset < 3 × 输入图像宽度
         * 示例：输入 1000×1000，left_offset=500 → 输出 1500×1000（仅在左侧添加 500 像素）
         */
        @Alias("left_offset")
        private Integer leftOffset;

        /**
         * 右侧添加像素数量
         * 默认值：0
         * 限制：left_offset + right_offset < 3 × 输入图像宽度
         * 示例：输入 1000×1000，right_offset=500 → 输出 1500×1000（仅在右侧添加 500 像素）
         */
        @Alias("right_offset")
        private Integer rightOffset;

        /**
         * 开启最佳质量模式
         * 默认值：false
         * 设置为 true 时图像细节更好，但耗时会成倍增加
         */
        @Alias("best_quality")
        private Boolean bestQuality;

        /**
         * 限制输出图像文件大小
         * 默认值：true
         * - 单边长度 <= 10000：输出图像限制为 5MB 以下
         * - 单边长度 > 10000：输出图像限制为 10MB 以下
         */
        @Alias("limit_image_size")
        private Boolean limitImageSize;

        /**
         * 添加"Generated by AI"水印
         * 默认值：true
         * 在输出图像左下角添加水印
         */
        @Alias("add_watermark")
        private Boolean addWatermark = false;
    }
}
