package com.cloud.picture.space.backend.api.volcano.model;


import cn.hutool.core.annotation.Alias;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * @Author: StartEnd
 * @CreateTime: 2026-03-21  10:37
 * @Description: TODO 文字图片生成请求类
 * <p>
 * 豆包AI Seedream-4.5图像生成请求类
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class GeneratePictureTaskRequest implements Serializable {

    /**
     * 模型名称
     * 必填，示例值：doubao-seedream-4-5-251128
     */

    private String model = "doubao-seedream-4-5-251128";

    /**
     * 图像生成提示词
     * 描述希望生成的图像内容，支持中文描述
     */
    private String prompt;

    /**
     * 图像尺寸
     * 可选值：["2K", "1K", "720P"]
     * 2K: 2048x2048, 1K: 1024x1024, 720P: 1280x720
     */
    @Alias("size")
    private String size = "2K";

    /**
     * 是否启用序列化图像生成
     * 可选值：["disabled", "enabled"]
     * 默认值：disabled
     */
    @Alias("sequential_image_generation")
    private String sequentialImageGeneration = "disabled";

    /**
     * 响应格式
     * 可选值：["url", "base64"]
     * url: 返回图像URL地址，base64: 返回Base64编码的图像数据
     */
    @Alias("response_format")
    private String responseFormat = "url";

    /**
     * 是否添加水印
     * 默认值：true
     * true: 添加"Generated by AI"水印，false: 不添加水印
     */
    @Alias("watermark")
    private Boolean watermark = true;

    /**
     * 是否启用流式响应
     * 默认值：false
     * true: 启用流式传输，false: 禁用流式传输
     */
    @Alias("stream")
    private Boolean stream = false;


    /**
     * 生成图像数量
     * 默认值：1
     * 取值范围：[1, 15]
     */
    @Alias("n")
    private Integer n = 1;


    /**
     * 提示词优化功能配置
     * 仅 doubao-seedream-4.5 支持该参数
     */
    @Alias("optimize_prompt_options")
    private OptimizePromptOptions optimizePromptOptions;

    /**
     * 提示词优化选项
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OptimizePromptOptions implements Serializable {

        /**
         * 提示词优化模式
         * 可选值：
         * - standard: 标准模式，生成内容的质量更高，耗时较长（默认值）
         * - fast: 快速模式，生成内容的耗时更短，质量一般；doubao-seedream-4.5 当前不支持
         */
        private String mode = "standard";
    }

}
