server:
  port: 8123
  servlet:
    context-path: /api
  # cookie 30 天过期
  session:
    cookie:
      max-age: 2592000

spring:
  application:
    name: yun-picture-space-service

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun-picture
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted #全局逻辑删除字段名
      logic-delete-value: 1 #逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为 0）


# 接口文档配置

knife4j:
  enable: true
  # 配置文档的标题、描述、作者、版本等信息
  openapi:
    title: "接口文档"
    version: "1.0.0"
    description: "接口文档"
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cloud.picture.space.backend.controller



# cos配置一般会在application-local.yml文件中配置而且不会同步到仓库中，
#如果仓库不是私有就不要同步进去，防止信息泄露
#这里仓库是私有，会同步
cos:
  client:
    host:
    secret-id:
    secret-key:
    region:
    bucket: yun-picture-1369372725


