server:
  port: 8123
  servlet:
    context-path: /api
  # cookie 30 天过期
  session:
    cookie:
      max-age: 2592000

spring:
  application:
    name: yun-picture-space-service

  #开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB

  # 激活配置文件
  profiles:
    active: local

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun-picture
    username: root
    password: 123456

  # Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000

  # session配置
  session:
    store-type: redis
    timeout: 2592000

  #空间图片分表
  shardingsphere:
    datasource:
      name: yun-picture
      yun-picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yun-picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yun-picture.picture
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm #使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.cloud.picture.space.backend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted #全局逻辑删除字段名
      logic-delete-value: 1 #逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为 0）
    enable-sql-runner: true

# 接口文档配置
knife4j:
  enable: true
  # 配置文档的标题、描述、作者、版本等信息
  openapi:
    title: "接口文档"
    version: "1.0.0"
    description: "接口文档"
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cloud.picture.space.backend.controller



# cos配置一般会在application-local.yml文件中配置而且不会同步到仓库中，
#如果仓库不是私有就不要同步进去，防止信息泄露
#这里仓库是私有，会同步
# 对象存储配置
#cos:
#  client:
#    host: xxxxxxx
#    secretId: xxxxxxx
#    secretKey: xxxxxxx
#    region: xxxxxxx
#    bucket: xxxxxxx


# 阿里云AI配置
aliYunAi:
  # 阿里百炼云自己的apiKey
  #apiKey: xxxxxx
  # 调用大模型地址（创建任务地址）
  visitURL: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation

# 豆包火山方舟AI
volcano:
#  apiKey: xxxxxxx
  #提示词扩充API地址
  visitPromptURL: https://ark.cn-beijing.volces.com/api/v3/chat/completions
  #文生图API地址
  visitURL: https://ark.cn-beijing.volces.com/api/v3/images/generations




thread-pool:
  core-pool-size: 10
  max-pool-size: 20
  keep-alive-time: 60
  queue-capacity: 200

#############Sa-Token配置##################
sa-token:
  is-log: true
